### ISSUE TITLE
Tsoha 1. code rewiew 

### ISSUE THREAD

**Issue by Termanty** [spirraw/Tsoha-Bootstrap#1]
Harjoitustyön ensimmäisen viikkon palautuksen jälkeen työ ei ole edennyt, joten minulla ei ole mitään kommentoitavaa. Paremmalla tsempillä ensi kerralla. 
- tero

**Comment by spirraw** [comment]
Myös kaikki 2. viikon tavoitteet olivat tehtyinä, tarkkasilmäisempää vertaisarviointia sitten ensi kerralla.æ
